name: delern_flutter
description: Spaced repetition learning system (Flutter version)

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

dependencies:
  device_info: ^0.4.0
  package_info: ^0.4.0
  url_launcher: ^5.0.1
  flutter_markdown: ^0.3.1
  http: ^0.12.0
  share: ^0.6.0
  shared_preferences: ^0.5.1
  intro_views_flutter: ^2.4.0
  quiver: ">=2.0.0 <3.0.0"
  built_collection: ^4.2.2
  built_value: ^6.6.0

  firebase_auth: ^0.8.2
  firebase_analytics: ^2.0.3
  firebase_database: ^2.0.2
  firebase_messaging: ^4.0.0
  firebase_crashlytics: ^0.1.0

  google_sign_in: ^4.0.1
  flutter_facebook_login: ^3.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  intl_translation: ^0.17.3
  mockito: ^3.0.0
  pedantic: ^1.0.0
  build_runner: ^1.6.1
  built_value_generator: ^6.6.0
  test: ^1.6.2

flutter:
  uses-material-design: true

  assets:
    # Onboarding.
    - images/card_sharing.png
    - images/child_learning.png
    - images/deck_creation.png

    # Icons for Sign In buttons and Navigation Drawer.
    - images/anonymous.jpg
    - images/google_sign_in.png
    - images/facebook_sign_in.png

    # Logo to display in e.g. About dialog.
    - images/ic_launcher.png

builders:
  built_value_generator: any
