name: flutter drive

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        device:
          # Flutter only supports 64-bit simulators:
          # https://flutter.dev/docs/get-started/install/macos.
          - "iPhone 8 (13.1)"
          - "iPhone 11 Pro Max (13.1)"
          - "iPad Pro (12.9-inch) (3rd generation) (13.1)"
    runs-on: macOS-latest
    env:
      FLUTTER_SDK_ROOT: /tmp/flutter
    steps:
      - name: "Print a list of simulators and start one"
        run: |
          echo 'Looking for specified device in the following list:'
          DEVICES=$(xcrun instruments -s)
          echo "$DEVICES"
          SIMULATOR_UDID=$(grep -F '${{ matrix.device }} [' <<<"${DEVICES?}" | \
              awk -F '[][]' '{ print $2 }')
          xcrun simctl boot "${SIMULATOR_UDID?}"
      - uses: actions/checkout@v1
      - name: "Install dependencies"
        run: |
          bundle install --deployment
          cd flutter
          bundle exec fastlane install_dependencies
          bundle exec fastlane install_debug_keys
      - name: "Pre-build app to unclutter test output"
        working-directory: flutter
        run: bundle exec fastlane ios build
      - name: "Build and run tests"
        working-directory: flutter
        run: |
          "${FLUTTER_SDK_ROOT?}/bin/flutter" drive --target test_driver/main.dart
